In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = np.random.randn(100)

In [3]:
a

array([-0.00926915,  0.11818688,  1.27068523,  0.2952604 ,  0.40973921,
        2.93961186,  0.61325811, -0.41055248, -0.537994  , -0.10905205,
       -0.42234175, -0.70250453,  1.26857255,  0.44688009, -0.60043919,
       -0.12034923,  1.0609929 ,  1.70958005,  0.09484033, -0.811955  ,
        0.37768049,  1.78788358, -0.14184178, -1.00821195,  0.4903664 ,
       -2.61857548, -0.69716773, -1.05425351,  0.47748425, -1.65993893,
       -0.04157048, -2.8002221 , -0.40991213,  0.92787411, -0.7217491 ,
       -0.78245132, -0.3509315 , -0.01417922,  1.58008759, -1.42258104,
        0.37086314,  0.41498939,  1.02517031,  2.45387104,  0.31328507,
        0.65766517, -0.18456903,  0.68455915,  0.14484286, -0.01100831,
       -0.0742342 ,  0.9015872 ,  0.93483274,  1.46469565, -0.93803571,
       -0.70236747, -0.13086265,  0.23520392,  0.6850889 ,  1.48633605,
       -1.17404789, -0.61673077,  0.41118399,  0.437606  ,  0.14753531,
        0.22419493,  0.23334889, -0.2185286 ,  2.81631309, -1.32

In [4]:
a = 10*a + 50

In [5]:
a

array([49.90730853, 51.18186876, 62.70685228, 52.95260402, 54.09739205,
       79.39611862, 56.13258111, 45.89447518, 44.62006004, 48.90947947,
       45.77658247, 42.97495474, 62.68572554, 54.46880095, 43.99560809,
       48.79650768, 60.60992903, 67.09580054, 50.94840335, 41.88044996,
       53.77680489, 67.87883579, 48.58158225, 39.91788052, 54.90366397,
       23.81424521, 43.02832268, 39.4574649 , 54.77484252, 33.40061073,
       49.58429519, 21.99777897, 45.90087869, 59.27874106, 42.78250901,
       42.17548679, 46.490685  , 49.85820784, 65.80087595, 35.77418957,
       53.70863135, 54.14989386, 60.25170313, 74.53871038, 53.13285066,
       56.57665174, 48.15430969, 56.84559146, 51.44842862, 49.88991691,
       49.257658  , 59.01587199, 59.34832743, 64.6469565 , 40.61964291,
       42.97632526, 48.69137355, 52.35203915, 56.85088901, 64.86336054,
       38.25952105, 43.83269235, 54.11183994, 54.37606001, 51.47535314,
       52.24194931, 52.33348893, 47.81471402, 78.1631309 , 36.75

In [6]:
a.shape

(100,)

In [7]:
a.shape = (5, 20)

In [8]:
a

array([[49.90730853, 51.18186876, 62.70685228, 52.95260402, 54.09739205,
        79.39611862, 56.13258111, 45.89447518, 44.62006004, 48.90947947,
        45.77658247, 42.97495474, 62.68572554, 54.46880095, 43.99560809,
        48.79650768, 60.60992903, 67.09580054, 50.94840335, 41.88044996],
       [53.77680489, 67.87883579, 48.58158225, 39.91788052, 54.90366397,
        23.81424521, 43.02832268, 39.4574649 , 54.77484252, 33.40061073,
        49.58429519, 21.99777897, 45.90087869, 59.27874106, 42.78250901,
        42.17548679, 46.490685  , 49.85820784, 65.80087595, 35.77418957],
       [53.70863135, 54.14989386, 60.25170313, 74.53871038, 53.13285066,
        56.57665174, 48.15430969, 56.84559146, 51.44842862, 49.88991691,
        49.257658  , 59.01587199, 59.34832743, 64.6469565 , 40.61964291,
        42.97632526, 48.69137355, 52.35203915, 56.85088901, 64.86336054],
       [38.25952105, 43.83269235, 54.11183994, 54.37606001, 51.47535314,
        52.24194931, 52.33348893, 47.81471402, 7

In [9]:
a.reshape(20, 5)

array([[49.90730853, 51.18186876, 62.70685228, 52.95260402, 54.09739205],
       [79.39611862, 56.13258111, 45.89447518, 44.62006004, 48.90947947],
       [45.77658247, 42.97495474, 62.68572554, 54.46880095, 43.99560809],
       [48.79650768, 60.60992903, 67.09580054, 50.94840335, 41.88044996],
       [53.77680489, 67.87883579, 48.58158225, 39.91788052, 54.90366397],
       [23.81424521, 43.02832268, 39.4574649 , 54.77484252, 33.40061073],
       [49.58429519, 21.99777897, 45.90087869, 59.27874106, 42.78250901],
       [42.17548679, 46.490685  , 49.85820784, 65.80087595, 35.77418957],
       [53.70863135, 54.14989386, 60.25170313, 74.53871038, 53.13285066],
       [56.57665174, 48.15430969, 56.84559146, 51.44842862, 49.88991691],
       [49.257658  , 59.01587199, 59.34832743, 64.6469565 , 40.61964291],
       [42.97632526, 48.69137355, 52.35203915, 56.85088901, 64.86336054],
       [38.25952105, 43.83269235, 54.11183994, 54.37606001, 51.47535314],
       [52.24194931, 52.33348893, 47.8

In [10]:
a

array([[49.90730853, 51.18186876, 62.70685228, 52.95260402, 54.09739205,
        79.39611862, 56.13258111, 45.89447518, 44.62006004, 48.90947947,
        45.77658247, 42.97495474, 62.68572554, 54.46880095, 43.99560809,
        48.79650768, 60.60992903, 67.09580054, 50.94840335, 41.88044996],
       [53.77680489, 67.87883579, 48.58158225, 39.91788052, 54.90366397,
        23.81424521, 43.02832268, 39.4574649 , 54.77484252, 33.40061073,
        49.58429519, 21.99777897, 45.90087869, 59.27874106, 42.78250901,
        42.17548679, 46.490685  , 49.85820784, 65.80087595, 35.77418957],
       [53.70863135, 54.14989386, 60.25170313, 74.53871038, 53.13285066,
        56.57665174, 48.15430969, 56.84559146, 51.44842862, 49.88991691,
        49.257658  , 59.01587199, 59.34832743, 64.6469565 , 40.61964291,
        42.97632526, 48.69137355, 52.35203915, 56.85088901, 64.86336054],
       [38.25952105, 43.83269235, 54.11183994, 54.37606001, 51.47535314,
        52.24194931, 52.33348893, 47.81471402, 7

In [11]:
a = a.reshape(20, 5)

In [12]:
a

array([[49.90730853, 51.18186876, 62.70685228, 52.95260402, 54.09739205],
       [79.39611862, 56.13258111, 45.89447518, 44.62006004, 48.90947947],
       [45.77658247, 42.97495474, 62.68572554, 54.46880095, 43.99560809],
       [48.79650768, 60.60992903, 67.09580054, 50.94840335, 41.88044996],
       [53.77680489, 67.87883579, 48.58158225, 39.91788052, 54.90366397],
       [23.81424521, 43.02832268, 39.4574649 , 54.77484252, 33.40061073],
       [49.58429519, 21.99777897, 45.90087869, 59.27874106, 42.78250901],
       [42.17548679, 46.490685  , 49.85820784, 65.80087595, 35.77418957],
       [53.70863135, 54.14989386, 60.25170313, 74.53871038, 53.13285066],
       [56.57665174, 48.15430969, 56.84559146, 51.44842862, 49.88991691],
       [49.257658  , 59.01587199, 59.34832743, 64.6469565 , 40.61964291],
       [42.97632526, 48.69137355, 52.35203915, 56.85088901, 64.86336054],
       [38.25952105, 43.83269235, 54.11183994, 54.37606001, 51.47535314],
       [52.24194931, 52.33348893, 47.8